In [5]:
#generate5 random integers b/w 1 to 100
import numpy as np
ran=np.random.randint(1,100,size=10)
ran

array([10, 84,  5, 10, 96, 35, 53, 21,  2, 71])

In [8]:
#genearte 5 random numbers of normal distribution
rann=np.random.normal(size=5)
rann


array([ 1.38553305, -0.96128856, -1.46637577, -0.95685629,  0.44822595])

In [26]:
#generate 2D array numbers randomaly
ran2d=np.random.randint(1,10,size=(2,2)) # here 1 ,10 is the numbers generate b/w them only
#we can als o genareate more 3d and 4d arrays also and numbers b/w 100,1000..
#like 
ran3d=np.random.randint(1,100,size=(2,3,3))
ran3d

array([[[77, 33, 94],
        [56, 38, 73],
        [91, 40, 42]],

       [[43, 17, 62],
        [85, 51,  3],
        [98, 41, 74]]])

In [33]:
#generate 2D array numbers randomaly by normal distribution
ran2d=np.random.normal(size=(2,2)) #here there is no need for to give b/w like randint above
print(ran2d)
#we can als o genareate more 3d and 4d arrays also and numbers by normal distribution
#like 
ran3d=np.random.normal(size=(2,3,3))
ran3d

[[ 0.64995934 -0.309957  ]
 [-0.1362732   1.32037587]]


array([[[ 0.97791054,  0.40009277, -0.39492576],
        [ 0.33422274, -0.47030629,  0.03040982],
        [ 0.86705393, -0.45917655,  0.74186136]],

       [[ 2.06698468, -0.58071959, -0.66242279],
        [-0.52920409, -0.72861391,  0.82857958],
        [ 1.39078802, -0.3262768 ,  0.06933778]]])

In [24]:
#we use masklike before
mask=ran3d<2 #printing slicing elements in 2d arry
#firt it print true are false elements
print(mask)
#next we print true like below

s=ran3d[mask]
print(s)
# another mw\ethod of above code is below
s=ran3d[ran3d<2]
s
#we can apply all 1d,2d,3d,4d......arrays

[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]]
[-0.29775526  0.10267346 -0.35199326  0.24637576 -0.15537175  1.34559723
 -1.17958952 -0.62701042 -0.79102277 -0.76779305 -0.53851449  0.01374384
  1.07556841 -1.00579994  0.14494021 -0.58071088  0.77127224 -0.6794442 ]


array([-0.29775526,  0.10267346, -0.35199326,  0.24637576, -0.15537175,
        1.34559723, -1.17958952, -0.62701042, -0.79102277, -0.76779305,
       -0.53851449,  0.01374384,  1.07556841, -1.00579994,  0.14494021,
       -0.58071088,  0.77127224, -0.6794442 ])

In [40]:
#multiplying arrays in numpy
b=np.random.randint(1,10,size=(3,3))
a=ran3d*b
print("multiflication of two matix is:",a)

multiflication of two matix is: [[[ 0.97791054  2.00046387 -1.57970305]
  [ 2.6737819  -0.94061259  0.24327856]
  [ 7.80348536 -0.45917655  2.96744544]]

 [[ 2.06698468 -2.90359796 -2.64969117]
  [-4.23363269 -1.45722782  6.62863665]
  [12.51709214 -0.3262768   0.27735114]]]


In [88]:
#reshaping the matrixes
arr=np.arange(1,5)
# we can respace 1d arrray into 2d array
r=arr.reshape((2,2))
r
arr=np.arange(1,10)
#we reshape 1d into 3x3 matrix
r=arr.reshape(3,3)
r
#resize
a=np.arange(1,10)
a.resize(2,5)
a
#ravel  this is covert any D dimentional data into one dimentional (1D)
r=arr.ravel
r
#flattensimilllar to ravel but not effect the original data it is only copy
flat_copy=a.flatten()
flat_copy


array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [93]:
#difference b/w ravel and flatten
a=np.array([[1,2],[2,3]])
r=a.ravel()
print(r)
f=a.flatten()
print(f)
r[1]
f[1]
a[1]


[1 2 2 3]
[1 2 2 3]


2

In [55]:
#aggrigate funtions
np.sum(arr)
np.max(arr)
np.min(arr)

1

In [58]:
#universal funtions
np.multiply(arr,2)
np.add(arr,6)

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [66]:
#trigrometric funtion
angle=np.array([0,np.pi/4,np.pi/2.3+np.pi/3,np.pi])
#sine

res_sin=np.sin(angle)
print(res_sin)
#cose
res_cos=np.cos(angle)
print("Cosine!",res_cos)

[0.00000000e+00 7.07106781e-01 6.65740120e-01 1.22464680e-16]
Cosine! [ 1.          0.70710678 -0.74618369 -1.        ]


In [70]:
#exponentials
a=np.array([1,2,3,4])
# natural exponential
e=np.exp(a)
print(e)
#natural log
l=np.log(a)
print(l)


[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]


In [75]:
#statical formulas
np.mean(a)
np.std(a)


1.118033988749895

In [80]:
#comparitons
np.greater(a,angle)

np.less(a,angle)
np.less_equal(a,angle)
np.greater_equal(a,angle)

array([ True,  True,  True,  True])

In [99]:
#creating array with a singleton dimenstion
c=np.array([[1,2,3],[2,3,4]])
print(c.shape)
#squeeze to romeve singleton dimentions
squee=c.squeeze()
print(squee)

#add on axes at index(expand)
expand=np.expand_dims(squee.shape,axis=1) # we can increase axies base on dimentions in array
expand


(2, 3)
[[1 2 3]
 [2 3 4]]


array([[2],
       [3]])

In [108]:
#spliting
n=np.arange(9)
x=np.split(n,3)
x
#array_split
xs=np.array_split(n,3)
xs
#np.hsplit and np.vsplit
n=np.array([[1,2,3],[2,3,4]])
xh=np.hsplit(n,3)
xh
xv=np.vsplit(n,2)
xv


[array([[1, 2, 3]]), array([[2, 3, 4]])]

In [109]:
#joining
#concatenate
a=np.array([1,2,3])
b=np.array([4,5,6])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [113]:
#horizontal stack
h=np.hstack((a,b))
h
#vertical stack
s
v=np.vstack((a,b))
v

array([[1, 2, 3],
       [4, 5, 6]])

In [114]:
#adding and removing elements
np.append(a,[7,7])

array([1, 2, 3, 7, 7])

In [116]:
#insert
np.insert(a,1,[1,2])  #here is 1 is the index where insert and [1,2] are values to insert

array([1, 1, 2, 2, 3])

In [119]:
# deleting single value
np.delete(a,2) # here 2 is the index where to delete the value in array 2
#deleting multiple values
np.delete(a,[0,2]) # same as above here deleting values b/w index 0 to 2

array([2])

In [120]:
#creating 2d array
d2=np.array([[1,2,3],[2,3,4],[4,5,6]])
#delete the second row
np.delete(d2,1,axis=0)



array([[1, 2, 3],
       [4, 5, 6]])