In [1]:
#numpy vs python

In [12]:
import numpy as np
lis=list(range(1000000))
arr=np.arange(1000000)

import sys
# size of array in python
print(f"size of lis:{sys.getsizeof(lis) }in bytes")
print(f"size of arr:{arr.nbytes} in bytes")
import time

#time taken by python for sum
s_time=time.time()
sumoflis=sum(lis)
e_time=time.time()
sumtimelis=(e_time-s_time)*1000
print(sumtimelis)
#time taken by numpy for sum
s_time=time.time()
sumofarr=np.sum(arr)
e_time=time.time()
sumtimearr=(e_time-s_time)*1000
print(sumtimearr)

         

size of lis:8000056in bytes
size of arr:4000000 in bytes
69.19574737548828
2.7666091918945312


In [14]:
narr=np.array([1,2,3,4,5])
narr
narr[2]

3

In [16]:
nar1=np.arange(10)
narr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
narr=np.arange(1,99)
narrr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [23]:
narrr=np.arange(1,4,1)
narrr

array([1, 2, 3])

In [26]:
a=np.zeros([2,3,4,1]) # we can not only zeroes and also ones ,twoes,.... and also number (arange)
a

array([[[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]]])

In [28]:
# memory usagre in numpy
arr_int32=np.array([122233,122334],dtype=np.int32) # and also different datatypes like fklaot ,long and more size also like 64,124

arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [34]:
arr_float=np.arange(1000,dtype=np.float64)

arr_float.dtype


dtype('float64')

In [35]:
afull_6=np.full([2,2],5) #it will fill with 5in 2x2 matrix
afull_6

array([[5, 5],
       [5, 5]])

In [37]:
#array operations in numpy
arr=np.add([1,2,3],[1,2,3])
#not only addition,multiply,dividion,substract and mod and power also
arr

array([2, 4, 6])

In [39]:
#and also logical operators like
a=np.array([1,2,3])
a1=np.array([1,2,3])
print(a==a1)
#not only equals,>,<,!=,<=,>=

[ True  True  True]


In [41]:
#slicing by indexing
a[1]
a[1:3]

array([2, 3])

In [ ]:
# slicing in 2D array by index
#two 2D array
a2=np.array([[1,2,3],
            [9,3,4],
            [2,3,5]])
a2[0:1,1:2]
a2[1:2,2:3]

In [63]:
mask=a2>2 #printing slicing elements in 2d arry
#firt it print true are false elements
print(mask)
#next we print true like below

s=a2[mask]
print(s)
# another mw\ethod of above code is below
s=a2[a2>2]
s
#we can apply all 1d,2d,3d,4d......arrays

[[False False  True]
 [ True  True  True]
 [False  True  True]]
[3 9 3 4 3 5]


array([3, 9, 3, 4, 3, 5])

In [66]:
#another oparations in array
ar=np.array([[1,2,3],[2,3,4],[4,5,6]],dtype=np.int64)
ar.T

array([[1, 2, 4],
       [2, 3, 5],
       [3, 4, 6]], dtype=int64)

In [81]:
#also swap axes
#they are teo way of swaping
sar=ar.swapaxes(1,0)
sar=np.swapaxes(ar,1,0)
sar

array([[1, 2, 4],
       [2, 3, 5],
       [3, 4, 6]], dtype=int64)

In [76]:
ar3=np.array([[[1,2,3]
               ,[2,3,4],
               [3,4,5]]
              ,[[98,7,7],
                [7,6,5],
                [6,5,5]]])
sae3=np.swapaxes(ar3,1,2)
sae3

array([[[ 1,  2,  3],
        [ 2,  3,  4],
        [ 3,  4,  5]],

       [[98,  7,  6],
        [ 7,  6,  5],
        [ 7,  5,  5]]])