NUMPY LIBRRARY

In [3]:
import numpy as np

In [5]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [7]:
import time
import sys

b=range(1000)
print(sys.getsizeof(5),len(b))

28 1000


In [11]:
c=np.arange(1000)
print(c.size*c.itemsize)

4000


In [17]:
size=100000
l1=range(size)
l2=range(size)
a1=np.arange(size)
a2=np.arange(size)

start=time.time()

result=[(x+y) for x,y in zip(l1,l2)]

result=[(x+y) for x,y in zip(l1,l2)]
#print(result)

print('python list took:' ,(time.time())*1000)

python list took: 1737524004226.6528


In [25]:
start=time.time()
result=a1+a2
print("numpy array took",(time.time())*1000)

numpy array took 1737524119362.2202


In [21]:
a=np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
a.ndim

2

In [23]:
a.itemsize

4

In [29]:
a.shape

(3, 2)

In [26]:
a=np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
a.itemsize

4

In [28]:
a.shape

(3, 2)

In [30]:
np.zeros((3,4)) #by default printing zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
np.ones((3,4)) #by default ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
l=np.arange(5)
l

array([0, 1, 2, 3, 4])

In [36]:
print('concatination example')
print(np.char.add(['hello','hi'],['abc','xyz']))

concatination example
['helloabc' 'hixyz']


In [55]:
print(np.char.multiply('hello',3)) # for duplication
print(np.char.center('hello',20,fillchar='-')) #for to hylite the requrie word at center by design like _-*^%$#@
print(np.char.capitalize('hello world')) #to uppercase first word of every word
print(np.char.title('how are you doing')) #to uppercase
print(np.char.upper('hello')) #to uppercase
print(np.char.lower('HELLO')) #lowercse
print(np.char.lower(['HELLO','World'])) #for two words
print(np.char.split('are you coming partuy')) #to sapare every word
print(np.char.splitlines('are ypu comming\n party')) #to saparete where \n 
print(np.char.strip(['nina','admin','ator'],'a')) # to cut the require letter or word from every word or line
print(np.char.join([':','-'],['day','ymd'])) #it is very useful because to split every word with our letter or symbal

print(np.char.replace('he is a good boy','is','was'))


hellohellohello
-------hello--------
Hello world
How Are You Doing
HELLO
hello
['hello' 'world']
['are', 'you', 'coming', 'partuy']
['are ypu comming', ' party']
['nin' 'dmin' 'tor']
['d:a:y' 'y-m-d']
he was a good boy


In [ ]:
print(np.char.join([':','-'],['day','ymd'])) #it is very useful because to split every word with our letter or symbal

print(np.char.replace('he is a good boy','is','was')) #for replace our requre word


In [22]:
s=np.random.randn(1)
s

array([-0.46344691])

In [25]:
f=np.linspace(0,1) #it is same as random number but it will where start and where end
f

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])